version: '3'

services:
  cuspdnode0:
    container_name: cuspdnode0
    image: "aphelion/cuspdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-cuspd.log}
    volumes:
      - ./build:/cuspd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  cuspdnode1:
    container_name: cuspdnode1
    image: "aphelion/cuspdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-cuspd.log}
    volumes:
      - ./build:/cuspd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  cuspdnode2:
    container_name: cuspdnode2
    image: "aphelion/cuspdnode"
    environment:
      - ID=2
      - LOG=${LOG:-cuspd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/cuspd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  cuspdnode3:
    container_name: cuspdnode3
    image: "aphelion/cuspdnode"
    environment:
      - ID=3
      - LOG=${LOG:-cuspd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/cuspd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

